// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Base64: typeof import('./src/components/Base64.vue')['default']
    FooterBottom: typeof import('./src/components/common/FooterBottom.vue')['default']
    GetIP: typeof import('./src/components/GetIP.vue')['default']
    LeftMenu: typeof import('./src/components/common/LeftMenu.vue')['default']
    Md5: typeof import('./src/components/Md5.vue')['default']
    NavBar: typeof import('./src/components/common/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
